
title: Jeremy Gaison
description: > # this means to ignore newlines until "baseurl:"
  Personal Website <img src="/images/ProfilePic.jpg" alt="Jeremy Gaison" width="250"/>


theme: jekyll-theme-slate
